title: Lucas Brito Website
description: A simple site hosted with GitHub Pages
author: Lucas Brito
theme: minima

# URL structure
baseurl: "bomberdude17.github.io"
url: "https://bomberdude17.github.io/"

# Build Settings
markdown: kramdown
plugins:
- jekyll-feed