title: Lucas Brito
description: >-
  Welcome to my personal portfolio. I'm a Computer Programmer passionate about video games!
  
  I am currently 29 years old and am in search of a permanent job.
author: Lucas Brito

# Site settings
baseurl: ""
url: "https://bomberdude17.github.io/"
theme: minima
# Navigation links in header
header_pages:
  - about.md
  - resume.md
  - work-experience.md
  - references.md
minima:
  social_links:
    github: "Bomberdude17"
    linkedin: "https://www.linkedin.com/in/lucas-brito-bomberdude17"
    twitter: "@bomberdude17"

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

<p align="center">
  <img src="/haha.jpg" alt="Lucas Brito" width="1000"/>
</p>
